//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP_SocialDrink {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP_SocialDrink.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional message.
        /// </summary>
        public static string am_fb {
            get {
                return ResourceManager.GetString("am_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drinking at.
        /// </summary>
        public static string app_title_DF {
            get {
                return ResourceManager.GetString("app_title_DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a place.
        /// </summary>
        public static string AppTitleAddLocal {
            get {
                return ResourceManager.GetString("AppTitleAddLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of brands.
        /// </summary>
        public static string AppTitleBrand {
            get {
                return ResourceManager.GetString("AppTitleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of categories.
        /// </summary>
        public static string AppTitleCategoria {
            get {
                return ResourceManager.GetString("AppTitleCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of drinks.
        /// </summary>
        public static string AppTitleDrink {
            get {
                return ResourceManager.GetString("AppTitleDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string b_camera {
            get {
                return ResourceManager.GetString("b_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string b_cancel {
            get {
                return ResourceManager.GetString("b_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit user.
        /// </summary>
        public static string b_edit_user {
            get {
                return ResourceManager.GetString("b_edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graph.
        /// </summary>
        public static string b_graph {
            get {
                return ResourceManager.GetString("b_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send map.
        /// </summary>
        public static string b_linkmap {
            get {
                return ResourceManager.GetString("b_linkmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send photo.
        /// </summary>
        public static string b_linkphoto {
            get {
                return ResourceManager.GetString("b_linkphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new place.
        /// </summary>
        public static string b_newplace {
            get {
                return ResourceManager.GetString("b_newplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string b_novo {
            get {
                return ResourceManager.GetString("b_novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string b_refresh {
            get {
                return ResourceManager.GetString("b_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string b_save {
            get {
                return ResourceManager.GetString("b_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send photo.
        /// </summary>
        public static string b_sendimage {
            get {
                return ResourceManager.GetString("b_sendimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send msg.
        /// </summary>
        public static string b_sendmessage {
            get {
                return ResourceManager.GetString("b_sendmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string b_share {
            get {
                return ResourceManager.GetString("b_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string b_sobre {
            get {
                return ResourceManager.GetString("b_sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string b01AddPlace {
            get {
                return ResourceManager.GetString("b01AddPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string busyIndicator {
            get {
                return ResourceManager.GetString("busyIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try finding it on Google.
        /// </summary>
        public static string button_nov_loc_address {
            get {
                return ResourceManager.GetString("button_nov_loc_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Try find it on.
        /// </summary>
        public static string button_nov_loc_google {
            get {
                return ResourceManager.GetString("button_nov_loc_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string button_use_gravar {
            get {
                return ResourceManager.GetString("button_use_gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Tel #.
        /// </summary>
        public static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send with drinks information.
        /// </summary>
        public static string cbSend {
            get {
                return ResourceManager.GetString("cbSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand or drink name.
        /// </summary>
        public static string check_brand {
            get {
                return ResourceManager.GetString("check_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drink type.
        /// </summary>
        public static string check_drink {
            get {
                return ResourceManager.GetString("check_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forgot password.
        /// </summary>
        public static string login_t_forgot {
            get {
                return ResourceManager.GetString("login_t_forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new account.
        /// </summary>
        public static string login_t_newaccount {
            get {
                return ResourceManager.GetString("login_t_newaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string login_t_password {
            get {
                return ResourceManager.GetString("login_t_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate location.
        /// </summary>
        public static string m_duplicado {
            get {
                return ResourceManager.GetString("m_duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong address.
        /// </summary>
        public static string m_endereco {
            get {
                return ResourceManager.GetString("m_endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close location.
        /// </summary>
        public static string m_fechado {
            get {
                return ResourceManager.GetString("m_fechado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet not connected. Try later..
        /// </summary>
        public static string m01 {
            get {
                return ResourceManager.GetString("m01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Connection lost. Try later..
        /// </summary>
        public static string m02 {
            get {
                return ResourceManager.GetString("m02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires access to your location. Do you agree? We can do this access?.
        /// </summary>
        public static string m03 {
            get {
                return ResourceManager.GetString("m03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string m04 {
            get {
                return ResourceManager.GetString("m04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connecting to server....
        /// </summary>
        public static string m05 {
            get {
                return ResourceManager.GetString("m05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be valid!.
        /// </summary>
        public static string m06 {
            get {
                return ResourceManager.GetString("m06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be valid!.
        /// </summary>
        public static string m07 {
            get {
                return ResourceManager.GetString("m07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid Login. Try again!.
        /// </summary>
        public static string m08 {
            get {
                return ResourceManager.GetString("m08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You must create another account..
        /// </summary>
        public static string m09 {
            get {
                return ResourceManager.GetString("m09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have this application access to location. Please change settings of your device..
        /// </summary>
        public static string m10 {
            get {
                return ResourceManager.GetString("m10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location is not functioning on this device.
        /// </summary>
        public static string m11 {
            get {
                return ResourceManager.GetString("m11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data unavailable.
        /// </summary>
        public static string m12 {
            get {
                return ResourceManager.GetString("m12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite signal is poor. Change your location and try again. Application will be terminate..
        /// </summary>
        public static string m13 {
            get {
                return ResourceManager.GetString("m13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while your position is determined....
        /// </summary>
        public static string m14 {
            get {
                return ResourceManager.GetString("m14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking for the satellite signal..
        /// </summary>
        public static string m15 {
            get {
                return ResourceManager.GetString("m15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking for the satellite signal...
        /// </summary>
        public static string m16 {
            get {
                return ResourceManager.GetString("m16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking for the satellite signal....
        /// </summary>
        public static string m17 {
            get {
                return ResourceManager.GetString("m17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places found nearby. Please add a new place. Click on + button..
        /// </summary>
        public static string m18 {
            get {
                return ResourceManager.GetString("m18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until : .
        /// </summary>
        public static string m19 {
            get {
                return ResourceManager.GetString("m19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drunk here: .
        /// </summary>
        public static string m20 {
            get {
                return ResourceManager.GetString("m20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your drunk here: .
        /// </summary>
        public static string m21 {
            get {
                return ResourceManager.GetString("m21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a drink type..
        /// </summary>
        public static string m22 {
            get {
                return ResourceManager.GetString("m22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must indicate the brand name..
        /// </summary>
        public static string m23 {
            get {
                return ResourceManager.GetString("m23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must indicate the number of doses..
        /// </summary>
        public static string m24 {
            get {
                return ResourceManager.GetString("m24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be valid!.
        /// </summary>
        public static string m25 {
            get {
                return ResourceManager.GetString("m25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm must be valid!.
        /// </summary>
        public static string m26 {
            get {
                return ResourceManager.GetString("m26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be the same!.
        /// </summary>
        public static string m27 {
            get {
                return ResourceManager.GetString("m27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male/Female not assigned!.
        /// </summary>
        public static string m28 {
            get {
                return ResourceManager.GetString("m28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coodinates found by satellite. Wait..
        /// </summary>
        public static string m30 {
            get {
                return ResourceManager.GetString("m30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your rank here: .
        /// </summary>
        public static string m31 {
            get {
                return ResourceManager.GetString("m31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rank places: .
        /// </summary>
        public static string m32 {
            get {
                return ResourceManager.GetString("m32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get user data drink from server....
        /// </summary>
        public static string m33 {
            get {
                return ResourceManager.GetString("m33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user data drink from server....
        /// </summary>
        public static string m34 {
            get {
                return ResourceManager.GetString("m34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set App data drink from server....
        /// </summary>
        public static string m35 {
            get {
                return ResourceManager.GetString("m35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one brand..
        /// </summary>
        public static string m36 {
            get {
                return ResourceManager.GetString("m36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one drink.
        /// </summary>
        public static string m37 {
            get {
                return ResourceManager.GetString("m37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand must be valid.
        /// </summary>
        public static string m38 {
            get {
                return ResourceManager.GetString("m38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This brand already exists.
        /// </summary>
        public static string m39 {
            get {
                return ResourceManager.GetString("m39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your drinks here:.
        /// </summary>
        public static string ms40 {
            get {
                return ResourceManager.GetString("ms40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total drinks here: .
        /// </summary>
        public static string ms41 {
            get {
                return ResourceManager.GetString("ms41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Drink at: .
        /// </summary>
        public static string ms42 {
            get {
                return ResourceManager.GetString("ms42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Drink at: .
        /// </summary>
        public static string ms43 {
            get {
                return ResourceManager.GetString("ms43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string ms44 {
            get {
                return ResourceManager.GetString("ms44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my recomendation:  .
        /// </summary>
        public static string ms45 {
            get {
                return ResourceManager.GetString("ms45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand or drink name:  .
        /// </summary>
        public static string ms46 {
            get {
                return ResourceManager.GetString("ms46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS number missing!.
        /// </summary>
        public static string ms47 {
            get {
                return ResourceManager.GetString("ms47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS to: .
        /// </summary>
        public static string ms48 {
            get {
                return ResourceManager.GetString("ms48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading nearby places....
        /// </summary>
        public static string ms49 {
            get {
                return ResourceManager.GetString("ms49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place name cannot be null!.
        /// </summary>
        public static string ms50 {
            get {
                return ResourceManager.GetString("ms50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category cannot be null!.
        /// </summary>
        public static string ms51 {
            get {
                return ResourceManager.GetString("ms51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be null!.
        /// </summary>
        public static string ms52 {
            get {
                return ResourceManager.GetString("ms52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving new place...Wait!.
        /// </summary>
        public static string ms53 {
            get {
                return ResourceManager.GetString("ms53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - during add new place. Try later..
        /// </summary>
        public static string ms54 {
            get {
                return ResourceManager.GetString("ms54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place saved!.
        /// </summary>
        public static string ms55 {
            get {
                return ResourceManager.GetString("ms55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        public static string ms56 {
            get {
                return ResourceManager.GetString("ms56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this image?.
        /// </summary>
        public static string ms57 {
            get {
                return ResourceManager.GetString("ms57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One address must be selected!.
        /// </summary>
        public static string ms58 {
            get {
                return ResourceManager.GetString("ms58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place already exists!.
        /// </summary>
        public static string ms59 {
            get {
                return ResourceManager.GetString("ms59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message sent to the staff.
        /// </summary>
        public static string ms60 {
            get {
                return ResourceManager.GetString("ms60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is missing!.
        /// </summary>
        public static string ms61 {
            get {
                return ResourceManager.GetString("ms61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send photo ....
        /// </summary>
        public static string ms62 {
            get {
                return ResourceManager.GetString("ms62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new album ....
        /// </summary>
        public static string ms63 {
            get {
                return ResourceManager.GetString("ms63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add photo to album ....
        /// </summary>
        public static string ms64 {
            get {
                return ResourceManager.GetString("ms64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo sent!.
        /// </summary>
        public static string ms65 {
            get {
                return ResourceManager.GetString("ms65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please, reduce size of message!.
        /// </summary>
        public static string ms66 {
            get {
                return ResourceManager.GetString("ms66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated account.
        /// </summary>
        public static string ms67 {
            get {
                return ResourceManager.GetString("ms67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully wrote new account!.
        /// </summary>
        public static string ms68 {
            get {
                return ResourceManager.GetString("ms68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was found in our data base. Please try another..
        /// </summary>
        public static string ms69 {
            get {
                return ResourceManager.GetString("ms69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot save your information. Try later!.
        /// </summary>
        public static string ms70 {
            get {
                return ResourceManager.GetString("ms70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be patient....
        /// </summary>
        public static string ms71 {
            get {
                return ResourceManager.GetString("ms71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total drinks: .
        /// </summary>
        public static string ms72 {
            get {
                return ResourceManager.GetString("ms72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select address.
        /// </summary>
        public static string nov_loc_address {
            get {
                return ResourceManager.GetString("nov_loc_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink name.
        /// </summary>
        public static string nov_loc_drink {
            get {
                return ResourceManager.GetString("nov_loc_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address(optional).
        /// </summary>
        public static string nov_loc_ende {
            get {
                return ResourceManager.GetString("nov_loc_ende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone(opcional).
        /// </summary>
        public static string nov_loc_fone {
            get {
                return ResourceManager.GetString("nov_loc_fone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to select.
        /// </summary>
        public static string nov_loc_g_tap {
            get {
                return ResourceManager.GetString("nov_loc_g_tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        public static string nov_loc_sel {
            get {
                return ResourceManager.GetString("nov_loc_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account.
        /// </summary>
        public static string nov_use_add {
            get {
                return ResourceManager.GetString("nov_use_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string nov_use_female {
            get {
                return ResourceManager.GetString("nov_use_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string nov_use_male {
            get {
                return ResourceManager.GetString("nov_use_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nov_use_nome {
            get {
                return ResourceManager.GetString("nov_use_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string nov_use_pass {
            get {
                return ResourceManager.GetString("nov_use_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm.
        /// </summary>
        public static string nov_use_passconf {
            get {
                return ResourceManager.GetString("nov_use_passconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string nov_use_profile {
            get {
                return ResourceManager.GetString("nov_use_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string novloc_categoria {
            get {
                return ResourceManager.GetString("novloc_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place name.
        /// </summary>
        public static string novloc_nomelocal {
            get {
                return ResourceManager.GetString("novloc_nomelocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my rank.
        /// </summary>
        public static string p11header {
            get {
                return ResourceManager.GetString("p11header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rank drinks.
        /// </summary>
        public static string p12header {
            get {
                return ResourceManager.GetString("p12header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby 50m.
        /// </summary>
        public static string p1header {
            get {
                return ResourceManager.GetString("p1header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 50 places.
        /// </summary>
        public static string p22header {
            get {
                return ResourceManager.GetString("p22header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my favorites.
        /// </summary>
        public static string p2header {
            get {
                return ResourceManager.GetString("p2header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 50 drinks.
        /// </summary>
        public static string p32header {
            get {
                return ResourceManager.GetString("p32header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 50 places.
        /// </summary>
        public static string p3header {
            get {
                return ResourceManager.GetString("p3header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string p4header {
            get {
                return ResourceManager.GetString("p4header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New place.
        /// </summary>
        public static string PTitleAddLocal {
            get {
                return ResourceManager.GetString("PTitleAddLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google 500m.
        /// </summary>
        public static string PTitleAddLocalGoogle {
            get {
                return ResourceManager.GetString("PTitleAddLocalGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select brand.
        /// </summary>
        public static string PTitleBrand {
            get {
                return ResourceManager.GetString("PTitleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PTitleCategoria {
            get {
                return ResourceManager.GetString("PTitleCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select drink.
        /// </summary>
        public static string PTitleDrink {
            get {
                return ResourceManager.GetString("PTitleDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap me.
        /// </summary>
        public static string radHubTile3 {
            get {
                return ResourceManager.GetString("radHubTile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select your dose.
        /// </summary>
        public static string sel_dose {
            get {
                return ResourceManager.GetString("sel_dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main message.
        /// </summary>
        public static string sm_fb {
            get {
                return ResourceManager.GetString("sm_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select brand name.
        /// </summary>
        public static string t_brand_name {
            get {
                return ResourceManager.GetString("t_brand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select drink type.
        /// </summary>
        public static string t_drink_type {
            get {
                return ResourceManager.GetString("t_drink_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo to send.
        /// </summary>
        public static string t_envia_foto {
            get {
                return ResourceManager.GetString("t_envia_foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new brand.
        /// </summary>
        public static string t_new_brand {
            get {
                return ResourceManager.GetString("t_new_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo to send.
        /// </summary>
        public static string t_photo {
            get {
                return ResourceManager.GetString("t_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before.
        /// </summary>
        public static string tBefore {
            get {
                return ResourceManager.GetString("tBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string tDose {
            get {
                return ResourceManager.GetString("tDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string tDoses {
            get {
                return ResourceManager.GetString("tDoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Messages.
        /// </summary>
        public static string title_fb {
            get {
                return ResourceManager.GetString("title_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand.
        /// </summary>
        public static string title_new_brand {
            get {
                return ResourceManager.GetString("title_new_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string tNow {
            get {
                return ResourceManager.GetString("tNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS number.
        /// </summary>
        public static string tSMS {
            get {
                return ResourceManager.GetString("tSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string tTotal {
            get {
                return ResourceManager.GetString("tTotal", resourceCulture);
            }
        }
    }
}
