//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Drink {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Social_Drink.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional message and images to share.
        /// </summary>
        public static string am_fb {
            get {
                return ResourceManager.GetString("am_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured Screen.
        /// </summary>
        public static string app_capture {
            get {
                return ResourceManager.GetString("app_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drinking at.
        /// </summary>
        public static string app_title_DF {
            get {
                return ResourceManager.GetString("app_title_DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a place.
        /// </summary>
        public static string AppTitleAddLocal {
            get {
                return ResourceManager.GetString("AppTitleAddLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of brands.
        /// </summary>
        public static string AppTitleBrand {
            get {
                return ResourceManager.GetString("AppTitleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of categories.
        /// </summary>
        public static string AppTitleCategoria {
            get {
                return ResourceManager.GetString("AppTitleCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change place.
        /// </summary>
        public static string AppTitleChange {
            get {
                return ResourceManager.GetString("AppTitleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of drinks.
        /// </summary>
        public static string AppTitleDrink {
            get {
                return ResourceManager.GetString("AppTitleDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string AppTitleFri {
            get {
                return ResourceManager.GetString("AppTitleFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of taxi.
        /// </summary>
        public static string AppTitleTaxi {
            get {
                return ResourceManager.GetString("AppTitleTaxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alcohol warning.
        /// </summary>
        public static string AVISO_Header {
            get {
                return ResourceManager.GetString("AVISO_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string b_camera {
            get {
                return ResourceManager.GetString("b_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string b_cancel {
            get {
                return ResourceManager.GetString("b_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capture.
        /// </summary>
        public static string b_capture {
            get {
                return ResourceManager.GetString("b_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkin.
        /// </summary>
        public static string b_checkin {
            get {
                return ResourceManager.GetString("b_checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear table.
        /// </summary>
        public static string b_clear {
            get {
                return ResourceManager.GetString("b_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string b_comprar {
            get {
                return ResourceManager.GetString("b_comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string b_delete {
            get {
                return ResourceManager.GetString("b_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string b_edit {
            get {
                return ResourceManager.GetString("b_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit user.
        /// </summary>
        public static string b_edit_user {
            get {
                return ResourceManager.GetString("b_edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graph.
        /// </summary>
        public static string b_graph {
            get {
                return ResourceManager.GetString("b_graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string b_hyper {
            get {
                return ResourceManager.GetString("b_hyper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place info.
        /// </summary>
        public static string b_info {
            get {
                return ResourceManager.GetString("b_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send map.
        /// </summary>
        public static string b_linkmap {
            get {
                return ResourceManager.GetString("b_linkmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send photo.
        /// </summary>
        public static string b_linkphoto {
            get {
                return ResourceManager.GetString("b_linkphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show map.
        /// </summary>
        public static string b_map {
            get {
                return ResourceManager.GetString("b_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new place.
        /// </summary>
        public static string b_newplace {
            get {
                return ResourceManager.GetString("b_newplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string b_novo {
            get {
                return ResourceManager.GetString("b_novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new place.
        /// </summary>
        public static string b_placenew {
            get {
                return ResourceManager.GetString("b_placenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promotion.
        /// </summary>
        public static string b_promotion {
            get {
                return ResourceManager.GetString("b_promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string b_refresh {
            get {
                return ResourceManager.GetString("b_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string b_save {
            get {
                return ResourceManager.GetString("b_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send photo.
        /// </summary>
        public static string b_sendimage {
            get {
                return ResourceManager.GetString("b_sendimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send msg.
        /// </summary>
        public static string b_sendmessage {
            get {
                return ResourceManager.GetString("b_sendmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string b_share {
            get {
                return ResourceManager.GetString("b_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string b_sobre {
            get {
                return ResourceManager.GetString("b_sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update now!.
        /// </summary>
        public static string b_update {
            get {
                return ResourceManager.GetString("b_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string b01AddPlace {
            get {
                return ResourceManager.GetString("b01AddPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string busyIndicator {
            get {
                return ResourceManager.GetString("busyIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try finding it on Google.
        /// </summary>
        public static string button_nov_loc_address {
            get {
                return ResourceManager.GetString("button_nov_loc_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Try find it on.
        /// </summary>
        public static string button_nov_loc_google {
            get {
                return ResourceManager.GetString("button_nov_loc_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string button_use_gravar {
            get {
                return ResourceManager.GetString("button_use_gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Tel #.
        /// </summary>
        public static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this picture and send it to Facebook or Twitter.
        /// </summary>
        public static string cap_save {
            get {
                return ResourceManager.GetString("cap_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string cbAll {
            get {
                return ResourceManager.GetString("cbAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send with drinks information.
        /// </summary>
        public static string cbSend {
            get {
                return ResourceManager.GetString("cbSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brand or drink name.
        /// </summary>
        public static string check_brand {
            get {
                return ResourceManager.GetString("check_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drink type.
        /// </summary>
        public static string check_drink {
            get {
                return ResourceManager.GetString("check_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows my medals and promotions I won.
        /// </summary>
        public static string dash_medals {
            get {
                return ResourceManager.GetString("dash_medals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows all the places I&apos;ve been and drinks that took.
        /// </summary>
        public static string dash_mytrack {
            get {
                return ResourceManager.GetString("dash_mytrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows the 10 best places near you via our database and top 50 brands.
        /// </summary>
        public static string dash_top10 {
            get {
                return ResourceManager.GetString("dash_top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Social Drink-Slot Machine Champions.
        /// </summary>
        public static string dash_top11 {
            get {
                return ResourceManager.GetString("dash_top11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Desligado {
            get {
                return ResourceManager.GetString("Desligado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drag and drop bottle here.
        /// </summary>
        public static string eDrop {
            get {
                return ResourceManager.GetString("eDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alcohol in your blood: .
        /// </summary>
        public static string eSangue {
            get {
                return ResourceManager.GetString("eSangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foursquare Server not available..
        /// </summary>
        public static string fsserver {
            get {
                return ResourceManager.GetString("fsserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Server not available..
        /// </summary>
        public static string googleserver {
            get {
                return ResourceManager.GetString("googleserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Ligado {
            get {
                return ResourceManager.GetString("Ligado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable Location.
        /// </summary>
        public static string LOCALI_Header {
            get {
                return ResourceManager.GetString("LOCALI_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses your location to find places near device position. Without this function the application does not work. See Privacy Policy in &quot;about&quot; button. .
        /// </summary>
        public static string LOCALItxt {
            get {
                return ResourceManager.GetString("LOCALItxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forgot password.
        /// </summary>
        public static string login_t_forgot {
            get {
                return ResourceManager.GetString("login_t_forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new account.
        /// </summary>
        public static string login_t_newaccount {
            get {
                return ResourceManager.GetString("login_t_newaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string login_t_password {
            get {
                return ResourceManager.GetString("login_t_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate location.
        /// </summary>
        public static string m_duplicado {
            get {
                return ResourceManager.GetString("m_duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong address.
        /// </summary>
        public static string m_endereco {
            get {
                return ResourceManager.GetString("m_endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close location.
        /// </summary>
        public static string m_fechado {
            get {
                return ResourceManager.GetString("m_fechado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet not connected. Try later..
        /// </summary>
        public static string m01 {
            get {
                return ResourceManager.GetString("m01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Connection lost. Try later..
        /// </summary>
        public static string m02 {
            get {
                return ResourceManager.GetString("m02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires access to your location. Do you agree? We can do this access?.
        /// </summary>
        public static string m03 {
            get {
                return ResourceManager.GetString("m03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string m04 {
            get {
                return ResourceManager.GetString("m04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connecting to server....
        /// </summary>
        public static string m05 {
            get {
                return ResourceManager.GetString("m05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be valid!.
        /// </summary>
        public static string m06 {
            get {
                return ResourceManager.GetString("m06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be valid!.
        /// </summary>
        public static string m07 {
            get {
                return ResourceManager.GetString("m07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid Login. Try again!.
        /// </summary>
        public static string m08 {
            get {
                return ResourceManager.GetString("m08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You must create another account..
        /// </summary>
        public static string m09 {
            get {
                return ResourceManager.GetString("m09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have this application access to location. Please change settings of your device..
        /// </summary>
        public static string m10 {
            get {
                return ResourceManager.GetString("m10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save OK.
        /// </summary>
        public static string m100 {
            get {
                return ResourceManager.GetString("m100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drinks.
        /// </summary>
        public static string m101 {
            get {
                return ResourceManager.GetString("m101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drinks.
        /// </summary>
        public static string m102 {
            get {
                return ResourceManager.GetString("m102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places.
        /// </summary>
        public static string m103 {
            get {
                return ResourceManager.GetString("m103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your HIFI network is not connected!.
        /// </summary>
        public static string m104 {
            get {
                return ResourceManager.GetString("m104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, go to Settings page and input your e-mail.
        /// </summary>
        public static string m105 {
            get {
                return ResourceManager.GetString("m105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data to server....
        /// </summary>
        public static string m106 {
            get {
                return ResourceManager.GetString("m106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, Finished!.
        /// </summary>
        public static string m107 {
            get {
                return ResourceManager.GetString("m107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data ....
        /// </summary>
        public static string m108 {
            get {
                return ResourceManager.GetString("m108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading data to send....
        /// </summary>
        public static string m109 {
            get {
                return ResourceManager.GetString("m109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location is not functioning on this device.
        /// </summary>
        public static string m11 {
            get {
                return ResourceManager.GetString("m11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to server....
        /// </summary>
        public static string m110 {
            get {
                return ResourceManager.GetString("m110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite signal is poor. Change your location and try again..
        /// </summary>
        public static string m12 {
            get {
                return ResourceManager.GetString("m12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data.
        /// </summary>
        public static string m128 {
            get {
                return ResourceManager.GetString("m128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Social Drinks records in your unit will exceed the size allowed. We can send the data to the server?.
        /// </summary>
        public static string m129 {
            get {
                return ResourceManager.GetString("m129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite signal is poor. Change your location and try again. Application will be terminate..
        /// </summary>
        public static string m13 {
            get {
                return ResourceManager.GetString("m13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change place.
        /// </summary>
        public static string m130 {
            get {
                return ResourceManager.GetString("m130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want change this place?.
        /// </summary>
        public static string m131 {
            get {
                return ResourceManager.GetString("m131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while your position is determined....
        /// </summary>
        public static string m14 {
            get {
                return ResourceManager.GetString("m14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking for the satellite signal..
        /// </summary>
        public static string m15 {
            get {
                return ResourceManager.GetString("m15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking for the satellite signal...
        /// </summary>
        public static string m16 {
            get {
                return ResourceManager.GetString("m16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looking for the satellite signal....
        /// </summary>
        public static string m17 {
            get {
                return ResourceManager.GetString("m17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places found nearby. Please add a new place. Click on + button..
        /// </summary>
        public static string m18 {
            get {
                return ResourceManager.GetString("m18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until : .
        /// </summary>
        public static string m19 {
            get {
                return ResourceManager.GetString("m19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drunk here: .
        /// </summary>
        public static string m20 {
            get {
                return ResourceManager.GetString("m20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your drunk here: .
        /// </summary>
        public static string m21 {
            get {
                return ResourceManager.GetString("m21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a drink type..
        /// </summary>
        public static string m22 {
            get {
                return ResourceManager.GetString("m22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must indicate the brand name..
        /// </summary>
        public static string m23 {
            get {
                return ResourceManager.GetString("m23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must indicate the number of doses..
        /// </summary>
        public static string m24 {
            get {
                return ResourceManager.GetString("m24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be valid!.
        /// </summary>
        public static string m25 {
            get {
                return ResourceManager.GetString("m25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm must be valid!.
        /// </summary>
        public static string m26 {
            get {
                return ResourceManager.GetString("m26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be the same!.
        /// </summary>
        public static string m27 {
            get {
                return ResourceManager.GetString("m27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male/Female not assigned!.
        /// </summary>
        public static string m28 {
            get {
                return ResourceManager.GetString("m28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coodinates found by satellite. Wait..
        /// </summary>
        public static string m30 {
            get {
                return ResourceManager.GetString("m30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your rank here: .
        /// </summary>
        public static string m31 {
            get {
                return ResourceManager.GetString("m31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rank places: .
        /// </summary>
        public static string m32 {
            get {
                return ResourceManager.GetString("m32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send user data drink to server....
        /// </summary>
        public static string m33 {
            get {
                return ResourceManager.GetString("m33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user data drink from server....
        /// </summary>
        public static string m34 {
            get {
                return ResourceManager.GetString("m34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set App data drink from server....
        /// </summary>
        public static string m35 {
            get {
                return ResourceManager.GetString("m35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one brand..
        /// </summary>
        public static string m36 {
            get {
                return ResourceManager.GetString("m36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one drink.
        /// </summary>
        public static string m37 {
            get {
                return ResourceManager.GetString("m37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand must be valid.
        /// </summary>
        public static string m38 {
            get {
                return ResourceManager.GetString("m38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This brand already exists.
        /// </summary>
        public static string m39 {
            get {
                return ResourceManager.GetString("m39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now! recommended places.
        /// </summary>
        public static string m499 {
            get {
                return ResourceManager.GetString("m499", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by name.
        /// </summary>
        public static string m500 {
            get {
                return ResourceManager.GetString("m500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by distance.
        /// </summary>
        public static string m501 {
            get {
                return ResourceManager.GetString("m501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by rating/checkin.
        /// </summary>
        public static string m502 {
            get {
                return ResourceManager.GetString("m502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by category.
        /// </summary>
        public static string m503 {
            get {
                return ResourceManager.GetString("m503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events nearby.
        /// </summary>
        public static string m504 {
            get {
                return ResourceManager.GetString("m504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events listed in.
        /// </summary>
        public static string m505 {
            get {
                return ResourceManager.GetString("m505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxis nearby.
        /// </summary>
        public static string m506 {
            get {
                return ResourceManager.GetString("m506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by name.
        /// </summary>
        public static string m600 {
            get {
                return ResourceManager.GetString("m600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by distance.
        /// </summary>
        public static string m601 {
            get {
                return ResourceManager.GetString("m601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by rating.
        /// </summary>
        public static string m602 {
            get {
                return ResourceManager.GetString("m602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by category.
        /// </summary>
        public static string m603 {
            get {
                return ResourceManager.GetString("m603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by checkin.
        /// </summary>
        public static string m604 {
            get {
                return ResourceManager.GetString("m604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by event.
        /// </summary>
        public static string m700 {
            get {
                return ResourceManager.GetString("m700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by distance.
        /// </summary>
        public static string m701 {
            get {
                return ResourceManager.GetString("m701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by date.
        /// </summary>
        public static string m702 {
            get {
                return ResourceManager.GetString("m702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by place.
        /// </summary>
        public static string m703 {
            get {
                return ResourceManager.GetString("m703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I Agree.
        /// </summary>
        public static string m73 {
            get {
                return ResourceManager.GetString("m73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept that this application access my location..
        /// </summary>
        public static string m74 {
            get {
                return ResourceManager.GetString("m74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string m75 {
            get {
                return ResourceManager.GetString("m75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I do not accept. Please close the application..
        /// </summary>
        public static string m76 {
            get {
                return ResourceManager.GetString("m76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Permission.
        /// </summary>
        public static string m77 {
            get {
                return ResourceManager.GetString("m77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you agree that this application access your location?.
        /// </summary>
        public static string m78 {
            get {
                return ResourceManager.GetString("m78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places offline.
        /// </summary>
        public static string m79 {
            get {
                return ResourceManager.GetString("m79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string m80 {
            get {
                return ResourceManager.GetString("m80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application do not work without this function. The application will be closed..
        /// </summary>
        public static string m81 {
            get {
                return ResourceManager.GetString("m81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet is not active or permission to location is disabled. You can work off line..
        /// </summary>
        public static string m85 {
            get {
                return ResourceManager.GetString("m85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To work offline create a fake place and later ajust it..
        /// </summary>
        public static string m86 {
            get {
                return ResourceManager.GetString("m86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you need a Taxi tap on taxi icon..
        /// </summary>
        public static string m87 {
            get {
                return ResourceManager.GetString("m87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap on the map to get route.
        /// </summary>
        public static string m870 {
            get {
                return ResourceManager.GetString("m870", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap in the cup to drink..
        /// </summary>
        public static string m88 {
            get {
                return ResourceManager.GetString("m88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have more than one TAXI in your contacts. Please leave only one..
        /// </summary>
        public static string m89 {
            get {
                return ResourceManager.GetString("m89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retrivied from Foursquare database.
        /// </summary>
        public static string m890 {
            get {
                return ResourceManager.GetString("m890", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the phone to send SMS!.
        /// </summary>
        public static string m90 {
            get {
                return ResourceManager.GetString("m90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap on icons for more details.
        /// </summary>
        public static string m900 {
            get {
                return ResourceManager.GetString("m900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is not null.
        /// </summary>
        public static string m91 {
            get {
                return ResourceManager.GetString("m91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Celular number missing!.
        /// </summary>
        public static string m92 {
            get {
                return ResourceManager.GetString("m92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your address destination is missing!.
        /// </summary>
        public static string m93 {
            get {
                return ResourceManager.GetString("m93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Place:.
        /// </summary>
        public static string m94 {
            get {
                return ResourceManager.GetString("m94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Address: .
        /// </summary>
        public static string m95 {
            get {
                return ResourceManager.GetString("m95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retrivied from Google database.
        /// </summary>
        public static string m950 {
            get {
                return ResourceManager.GetString("m950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .Name: .
        /// </summary>
        public static string m96 {
            get {
                return ResourceManager.GetString("m96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retrivied from Nokia database.
        /// </summary>
        public static string m960 {
            get {
                return ResourceManager.GetString("m960", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Celular: .
        /// </summary>
        public static string m97 {
            get {
                return ResourceManager.GetString("m97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . I am here: .
        /// </summary>
        public static string m98 {
            get {
                return ResourceManager.GetString("m98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Destination: .
        /// </summary>
        public static string m99 {
            get {
                return ResourceManager.GetString("m99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on the cup.
        /// </summary>
        public static string ms107 {
            get {
                return ResourceManager.GetString("ms107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, QR Code was read.
        /// </summary>
        public static string ms110 {
            get {
                return ResourceManager.GetString("ms110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is not a Social Drink QR Code!.
        /// </summary>
        public static string ms111 {
            get {
                return ResourceManager.GetString("ms111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login on server....
        /// </summary>
        public static string ms121 {
            get {
                return ResourceManager.GetString("ms121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seaching satellite....
        /// </summary>
        public static string ms122 {
            get {
                return ResourceManager.GetString("ms122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading NOKIA database ....
        /// </summary>
        public static string ms123 {
            get {
                return ResourceManager.GetString("ms123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading GOOGLE database ....
        /// </summary>
        public static string ms124 {
            get {
                return ResourceManager.GetString("ms124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reading FOURSQUARE database ....
        /// </summary>
        public static string ms125 {
            get {
                return ResourceManager.GetString("ms125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I recommend this application: Social Drink.
        /// </summary>
        public static string ms126 {
            get {
                return ResourceManager.GetString("ms126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places.
        /// </summary>
        public static string ms127 {
            get {
                return ResourceManager.GetString("ms127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are around .
        /// </summary>
        public static string ms128 {
            get {
                return ResourceManager.GetString("ms128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the place. .
        /// </summary>
        public static string ms129 {
            get {
                return ResourceManager.GetString("ms129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a place from above list - double tap.
        /// </summary>
        public static string ms130 {
            get {
                return ResourceManager.GetString("ms130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drag and drop the bottle inside the red rectangle.
        /// </summary>
        public static string ms131 {
            get {
                return ResourceManager.GetString("ms131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on cup several times until to form a pyramid.
        /// </summary>
        public static string ms132 {
            get {
                return ResourceManager.GetString("ms132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your drinks here:.
        /// </summary>
        public static string ms40 {
            get {
                return ResourceManager.GetString("ms40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total drinks here: .
        /// </summary>
        public static string ms41 {
            get {
                return ResourceManager.GetString("ms41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Drink at: .
        /// </summary>
        public static string ms42 {
            get {
                return ResourceManager.GetString("ms42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Drink at: .
        /// </summary>
        public static string ms43 {
            get {
                return ResourceManager.GetString("ms43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string ms44 {
            get {
                return ResourceManager.GetString("ms44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my recomendation:  .
        /// </summary>
        public static string ms45 {
            get {
                return ResourceManager.GetString("ms45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand or drink name:  .
        /// </summary>
        public static string ms46 {
            get {
                return ResourceManager.GetString("ms46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS number missing!.
        /// </summary>
        public static string ms47 {
            get {
                return ResourceManager.GetString("ms47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS to: .
        /// </summary>
        public static string ms48 {
            get {
                return ResourceManager.GetString("ms48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading nearby places....
        /// </summary>
        public static string ms49 {
            get {
                return ResourceManager.GetString("ms49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place name cannot be null!.
        /// </summary>
        public static string ms50 {
            get {
                return ResourceManager.GetString("ms50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category cannot be null!.
        /// </summary>
        public static string ms51 {
            get {
                return ResourceManager.GetString("ms51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be null!.
        /// </summary>
        public static string ms52 {
            get {
                return ResourceManager.GetString("ms52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving new place...Wait!.
        /// </summary>
        public static string ms53 {
            get {
                return ResourceManager.GetString("ms53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - during add new place. Try later..
        /// </summary>
        public static string ms54 {
            get {
                return ResourceManager.GetString("ms54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place saved!.
        /// </summary>
        public static string ms55 {
            get {
                return ResourceManager.GetString("ms55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        public static string ms56 {
            get {
                return ResourceManager.GetString("ms56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this image?.
        /// </summary>
        public static string ms57 {
            get {
                return ResourceManager.GetString("ms57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One address must be selected!.
        /// </summary>
        public static string ms58 {
            get {
                return ResourceManager.GetString("ms58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place already exists!.
        /// </summary>
        public static string ms59 {
            get {
                return ResourceManager.GetString("ms59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message sent to the staff.
        /// </summary>
        public static string ms60 {
            get {
                return ResourceManager.GetString("ms60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is missing!.
        /// </summary>
        public static string ms61 {
            get {
                return ResourceManager.GetString("ms61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send photo ....
        /// </summary>
        public static string ms62 {
            get {
                return ResourceManager.GetString("ms62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new album ....
        /// </summary>
        public static string ms63 {
            get {
                return ResourceManager.GetString("ms63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add photo to album ....
        /// </summary>
        public static string ms64 {
            get {
                return ResourceManager.GetString("ms64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo sent!.
        /// </summary>
        public static string ms65 {
            get {
                return ResourceManager.GetString("ms65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please, reduce size of message!.
        /// </summary>
        public static string ms66 {
            get {
                return ResourceManager.GetString("ms66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated account.
        /// </summary>
        public static string ms67 {
            get {
                return ResourceManager.GetString("ms67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully wrote new account!.
        /// </summary>
        public static string ms68 {
            get {
                return ResourceManager.GetString("ms68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was found in our data base. Please try another..
        /// </summary>
        public static string ms69 {
            get {
                return ResourceManager.GetString("ms69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot save your information. Try later!.
        /// </summary>
        public static string ms70 {
            get {
                return ResourceManager.GetString("ms70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be patient....
        /// </summary>
        public static string ms71 {
            get {
                return ResourceManager.GetString("ms71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total drinks: .
        /// </summary>
        public static string ms72 {
            get {
                return ResourceManager.GetString("ms72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network access.
        /// </summary>
        public static string NET_Header {
            get {
                return ResourceManager.GetString("NET_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia Server not available..
        /// </summary>
        public static string nokiaserver {
            get {
                return ResourceManager.GetString("nokiaserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select address.
        /// </summary>
        public static string nov_loc_address {
            get {
                return ResourceManager.GetString("nov_loc_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be at the new location. The coordinates are passed by the satellite. See below..
        /// </summary>
        public static string nov_loc_aviso {
            get {
                return ResourceManager.GetString("nov_loc_aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink name.
        /// </summary>
        public static string nov_loc_drink {
            get {
                return ResourceManager.GetString("nov_loc_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string nov_loc_ende {
            get {
                return ResourceManager.GetString("nov_loc_ende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone(opcional).
        /// </summary>
        public static string nov_loc_fone {
            get {
                return ResourceManager.GetString("nov_loc_fone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to select.
        /// </summary>
        public static string nov_loc_g_tap {
            get {
                return ResourceManager.GetString("nov_loc_g_tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        public static string nov_loc_sel {
            get {
                return ResourceManager.GetString("nov_loc_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account.
        /// </summary>
        public static string nov_use_add {
            get {
                return ResourceManager.GetString("nov_use_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string nov_use_female {
            get {
                return ResourceManager.GetString("nov_use_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string nov_use_male {
            get {
                return ResourceManager.GetString("nov_use_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nov_use_nome {
            get {
                return ResourceManager.GetString("nov_use_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string nov_use_pass {
            get {
                return ResourceManager.GetString("nov_use_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm.
        /// </summary>
        public static string nov_use_passconf {
            get {
                return ResourceManager.GetString("nov_use_passconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string nov_use_profile {
            get {
                return ResourceManager.GetString("nov_use_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string novloc_categoria {
            get {
                return ResourceManager.GetString("novloc_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place name.
        /// </summary>
        public static string novloc_nomelocal {
            get {
                return ResourceManager.GetString("novloc_nomelocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my track.
        /// </summary>
        public static string p111header {
            get {
                return ResourceManager.GetString("p111header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my drinks here.
        /// </summary>
        public static string p11header {
            get {
                return ResourceManager.GetString("p11header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my drinks.
        /// </summary>
        public static string p121header {
            get {
                return ResourceManager.GetString("p121header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 50 brands.
        /// </summary>
        public static string p122header {
            get {
                return ResourceManager.GetString("p122header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 10 places.
        /// </summary>
        public static string p12header {
            get {
                return ResourceManager.GetString("p12header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 champions.
        /// </summary>
        public static string p12slotheader {
            get {
                return ResourceManager.GetString("p12slotheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places.
        /// </summary>
        public static string p1header {
            get {
                return ResourceManager.GetString("p1header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 10 places.
        /// </summary>
        public static string p22header {
            get {
                return ResourceManager.GetString("p22header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my favorites.
        /// </summary>
        public static string p2header {
            get {
                return ResourceManager.GetString("p2header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.
        /// </summary>
        public static string P2Main {
            get {
                return ResourceManager.GetString("P2Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drinks here.
        /// </summary>
        public static string p311header {
            get {
                return ResourceManager.GetString("p311header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string p321header {
            get {
                return ResourceManager.GetString("p321header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 50 drinks.
        /// </summary>
        public static string p32header {
            get {
                return ResourceManager.GetString("p32header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top 50 places.
        /// </summary>
        public static string p3header {
            get {
                return ResourceManager.GetString("p3header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string P3Main {
            get {
                return ResourceManager.GetString("P3Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string p4header {
            get {
                return ResourceManager.GetString("p4header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string P4Main {
            get {
                return ResourceManager.GetString("P4Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places.
        /// </summary>
        public static string p91header {
            get {
                return ResourceManager.GetString("p91header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promotion.
        /// </summary>
        public static string PageQR {
            get {
                return ResourceManager.GetString("PageQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PageTitleEdit {
            get {
                return ResourceManager.GetString("PageTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trial ended.
        /// </summary>
        public static string PageTitleTrial {
            get {
                return ResourceManager.GetString("PageTitleTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place map.
        /// </summary>
        public static string place_map {
            get {
                return ResourceManager.GetString("place_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New place.
        /// </summary>
        public static string PTitleAddLocal {
            get {
                return ResourceManager.GetString("PTitleAddLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google 500m.
        /// </summary>
        public static string PTitleAddLocalGoogle {
            get {
                return ResourceManager.GetString("PTitleAddLocalGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select brand.
        /// </summary>
        public static string PTitleBrand {
            get {
                return ResourceManager.GetString("PTitleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete brands.
        /// </summary>
        public static string PTitleBrandDel {
            get {
                return ResourceManager.GetString("PTitleBrandDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PTitleCategoria {
            get {
                return ResourceManager.GetString("PTitleCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select drink.
        /// </summary>
        public static string PTitleDrink {
            get {
                return ResourceManager.GetString("PTitleDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select friends.
        /// </summary>
        public static string PTitleFriends {
            get {
                return ResourceManager.GetString("PTitleFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call a taxi.
        /// </summary>
        public static string PTitleTaxi {
            get {
                return ResourceManager.GetString("PTitleTaxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample.
        /// </summary>
        public static string QRSample {
            get {
                return ResourceManager.GetString("QRSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the QR code Card and send to Bar that will participate in the promotion..
        /// </summary>
        public static string QRT1 {
            get {
                return ResourceManager.GetString("QRT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each card is a promotion of a certain brand.
        /// </summary>
        public static string QRT2 {
            get {
                return ResourceManager.GetString("QRT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your drink is in our promotion request your card.
        /// </summary>
        public static string QRT3 {
            get {
                return ResourceManager.GetString("QRT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this place has promotion aim the camera to the card with the QR Code that the manager gave you..
        /// </summary>
        public static string QRTexto {
            get {
                return ResourceManager.GetString("QRTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap me.
        /// </summary>
        public static string radHubTile3 {
            get {
                return ResourceManager.GetString("radHubTile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select your dose.
        /// </summary>
        public static string sel_dose {
            get {
                return ResourceManager.GetString("sel_dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send to server.
        /// </summary>
        public static string sendinfo {
            get {
                return ResourceManager.GetString("sendinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail.
        /// </summary>
        public static string set_email {
            get {
                return ResourceManager.GetString("set_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main message.
        /// </summary>
        public static string sm_fb {
            get {
                return ResourceManager.GetString("sm_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select brand name.
        /// </summary>
        public static string t_brand_name {
            get {
                return ResourceManager.GetString("t_brand_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select drink type.
        /// </summary>
        public static string t_drink_type {
            get {
                return ResourceManager.GetString("t_drink_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo to send.
        /// </summary>
        public static string t_envia_foto {
            get {
                return ResourceManager.GetString("t_envia_foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new brand.
        /// </summary>
        public static string t_new_brand {
            get {
                return ResourceManager.GetString("t_new_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo to share.
        /// </summary>
        public static string t_photo {
            get {
                return ResourceManager.GetString("t_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call a Taxi.
        /// </summary>
        public static string taxi_b_call {
            get {
                return ResourceManager.GetString("taxi_b_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Taxi phone number.
        /// </summary>
        public static string taxi_b_novofone {
            get {
                return ResourceManager.GetString("taxi_b_novofone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS to Taxi with map.
        /// </summary>
        public static string taxi_b_sms {
            get {
                return ResourceManager.GetString("taxi_b_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your Cel number.
        /// </summary>
        public static string taxi_cel_num {
            get {
                return ResourceManager.GetString("taxi_cel_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your address destination.
        /// </summary>
        public static string taxi_destino {
            get {
                return ResourceManager.GetString("taxi_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your last name.
        /// </summary>
        public static string taxi_last_name {
            get {
                return ResourceManager.GetString("taxi_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before.
        /// </summary>
        public static string tBefore {
            get {
                return ResourceManager.GetString("tBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string tDose {
            get {
                return ResourceManager.GetString("tDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string tDoses {
            get {
                return ResourceManager.GetString("tDoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change from: .
        /// </summary>
        public static string textBlock1 {
            get {
                return ResourceManager.GetString("textBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to: (select from the list below).
        /// </summary>
        public static string textBlock3 {
            get {
                return ResourceManager.GetString("textBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Messages.
        /// </summary>
        public static string title_fb {
            get {
                return ResourceManager.GetString("title_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand.
        /// </summary>
        public static string title_new_brand {
            get {
                return ResourceManager.GetString("title_new_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR CODE CARD PROMOTION.
        /// </summary>
        public static string TitleQR {
            get {
                return ResourceManager.GetString("TitleQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string tNow {
            get {
                return ResourceManager.GetString("tNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my collection.
        /// </summary>
        public static string trofeu {
            get {
                return ResourceManager.GetString("trofeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS number.
        /// </summary>
        public static string tSMS {
            get {
                return ResourceManager.GetString("tSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string tTotal {
            get {
                return ResourceManager.GetString("tTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. The trial period ended. If you want to buy this application click the buy button..
        /// </summary>
        public static string ttrial {
            get {
                return ResourceManager.GetString("ttrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update your database drink .
        /// </summary>
        public static string txt_update {
            get {
                return ResourceManager.GetString("txt_update", resourceCulture);
            }
        }
    }
}
